/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package showVersions;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;


public class AppTest {
    private App classUnderTest;

    @Before
    public void setUp() throws Exception {
        classUnderTest = new App();
        classUnderTest.initJack();
    }

    @Test
    public void getJackVersion() {
        assertNotNull(classUnderTest.getJackVersion());
    }

    @Test
    public void getJniVersion() {
        assertNotNull(classUnderTest.getJniVersion());
    }
}
